"""Makes small WebP copies of the bundled photos so the store does not download 900px JPGs for 200px cards.

For every public/images/**/<name>.jpg it writes <name>.webp (full size) plus <name>-480.webp and
<name>-160.webp, and lists the converted paths in src/data/imageVariants.ts. The JPGs stay: the 3D
studio textures and og:image use them. Run again after `npm run sync:fabrics` adds new photos:

    python -m pip install pillow
    python scripts/optimize-images.py
"""
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / 'public'
WIDTHS = (480, 160)
QUALITY = 78
SKIP = {'images/hero/luxury_atelier_hero.jpg'}  # only used as og:image, never rendered on the page


def save(im: Image.Image, out: Path, width: int | None) -> None:
    if width and im.width > width:
        im = im.resize((width, round(im.height * width / im.width)), Image.LANCZOS)
    im.save(out, 'WEBP', quality=QUALITY, method=6)


def main() -> None:
    done, before, after = [], 0, 0
    for jpg in sorted((PUBLIC / 'images').rglob('*.jpg')):
        rel = jpg.relative_to(PUBLIC).as_posix()
        if rel in SKIP:
            continue
        with Image.open(jpg) as src:
            im = src.convert('RGB')
            targets = [(jpg.with_suffix('.webp'), None)] + [(jpg.with_name(f'{jpg.stem}-{w}.webp'), w) for w in WIDTHS]
            for out, width in targets:
                if not out.exists() or out.stat().st_mtime < jpg.stat().st_mtime:
                    save(im, out, width)
        before += jpg.stat().st_size
        after += jpg.with_suffix('.webp').stat().st_size
        done.append((rel, im.width))

    lines = ',\n'.join(f"  ['{p}', {w}]" for p, w in done)
    (ROOT / 'src' / 'data' / 'imageVariants.ts').write_text(
        '// Generated by scripts/optimize-images.py — do not edit by hand.\n'
        '/** Bundled photos (path -> original width) that have WebP copies at full size, 480px and 160px wide. */\n'
        f'export const IMAGE_VARIANTS: ReadonlyMap<string, number> = new Map<string, number>([\n{lines},\n]);\n',
        encoding='utf-8',
    )
    print(f'{len(done)} photos: JPG {before / 1e6:.1f} MB -> full-size WebP {after / 1e6:.1f} MB')


if __name__ == '__main__':
    main()
